#!/usr/bin/env bash
set -eu

echo "🔵 build"

echo "[---] DOCKERFILE_PATH: ${DOCKERFILE_PATH}"
echo "[---] DOCKER_REPO: ${DOCKER_REPO}"
echo "[---] DOCKER_TAG: ${DOCKER_TAG}"
echo "[---] IMAGE_NAME: ${IMAGE_NAME}"
echo "[---] SOURCE_BRANCH: ${SOURCE_BRANCH}"
echo "[---] SOURCE_COMMIT: ${SOURCE_COMMIT}"
echo "[---] COMMIT_MSG: ${COMMIT_MSG}"

docker -v

echo "✅ buildin"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"


for FILE in ${DOCKERFILE_PATH%.*}.*
do
    TARGET_ARCH=$(echo "${FILE}" | cut -d '.' -f 2)

    echo ${TARGET_ARCH}

    docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                 --build-arg VCS_REF=`git rev-parse --short HEAD` \
                 --build-arg ARCH=${TARGET_ARCH} \
                 -f ${FILE} -t $IMAGE_NAME-${TARGET_ARCH} .
done


echo "✅ images built:"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
docker image ls

