#!/usr/bin/env bash
set -eu

echo "🔵 push"

echo "✅ Pushin images"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

for FILE in ${DOCKERFILE_PATH%.*}.*
do
    TARGET_ARCH=$(echo "${FILE}" | cut -d '.' -f 2)

    case "$TARGET_ARCH" in
        *arm32v5)
            PLATFORMS="linux/arm"
            ;;
        *arm32v6)
            PLATFORMS="linux/arm"
            ;;
        *arm32v7)
            PLATFORMS="linux/arm"
            ;;
        *arm64v8)
            PLATFORMS="linux/arm64"
            ;;
        *)
           echo "Unknown target architecture ${TARGET_ARCH}"
           exit 0
           ;;
    esac

    docker push ${IMAGE_NAME}-${TARGET_ARCH}

done



