#!/usr/bin/env bash
set -eu

echo "🔵 push"

echo "✅ Pushingimages}"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"


for FILE in ${DOCKERFILE_PATH%.*}.*
do
    TARGET_ARCH=$(echo "${FILE}" | cut -d '.' -f 2)

    docker push ${IMAGE_NAME}-${TARGET_ARCH}

done


